name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  python-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Run Python checks
        uses: ./.github/actions/project-ci
        with:
          stack: python
          python-version: "3.10"

  node-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Run Node checks
        uses: ./.github/actions/project-ci
        with:
          node-version: "24"
          stack: node